application: rationalize-it
version: alpha-1
runtime: php
api_version: 1

handlers:
  - url: /(.+)
    static_files: \1
    upload: (.*)

  - url: /
    static_files: ./index.html
    upload: ./index.html

  - url: /(.+\.php)$
    script: \1

